name: Crypto Currency NOW
favicon: null
layout_spectrum: 0.5108584780246019
typography_spectrum: 0.7306680255569518
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.06860727444291115
  lightness: 0.12241972610354424
  saturation: 0.9991691862232983
  rhythmicContrast: 0.9022914122324437
purpose: []
